title: Hello there! This is Ashim
email: justayyme@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi my name is Ashim. I am a programmer.I started off as a web developer but
  then soon I started learning mobile application development as well.
baseurl: ""
url: "https://uashim.com.np"
github_username: ayyshim
facebook_username: ayyshim
instagram_username: ayyshim

skills:
  - name: "Javascript"
    image: "js.png"
  - name: "ReactJS"
    image: "react_js.png"
  - name: "Dart"
    image: "dart.png"
  - name: "flutter"
    image: "flutter.png"
  - name: "python"
    image: "python.png"
  - name: "android"
    image: "android.png"

academics:
  - level: "Bachelor of Computer Applications (2018 - Present)"
    institutes:
      - "Tula's Institute, Dhoolkot, Dehradun, India"
  - level: "+2 Management"
    institutes:
      - "Pentagon Int'l college, Tinkune, Kathmandu, Nepal"
      - "Tilottama Campus, Yogikuti, Rupandehi, Nepal"
work-experience:
  - level: "Lead Developer / Application Manager (2021 - Present)"
    company: "G.G. Maidan (Pvt.) Ltd., Kathmandu"
    companyLink: "https://ggmaidan.com"
  - level: "Freelancing (2018 - Present)"
  - level: "Android Developer (2021 - Present)"
    company: "BSAI Techno Sales, Kathmandu"
    companyLink: "https://bsaitechnosales.com"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      isPost: true
      permalink: /works/:title

plugins:
  - jekyll-feed
